openapi: 3.0.1
info:
  title: Petstore API
  version: "1.0.0"
  description: API para la gestión de una tienda de mascotas
servers:
  - url: http://localhost:8080
  
paths:
  /api/adoptions/{petId}/adopt:
    post:
      tags:
        - Adoptions
      summary: Adoptar una mascota
      description: Permite que un usuario adopte una mascota específica.
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
          description: ID de la mascota a adoptar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                  description: ID del usuario que adopta la mascota
      responses:
        '200':
          description: Adopción exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Adopción realizada con éxito
                  pet:
                    $ref: '#/components/schemas/Pet'
        '400':
          description: Mascota ya adoptada
        '404':
          description: Mascota o usuario no encontrado
        '500':
          description: Error interno del servidor

components:
  schemas:
    Pet:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        species:
          type: string
        adopted:
          type: boolean
        owner:
          type: string